In [81]:
import numpy as np

np.set_printoptions(suppress=True, precision=3)
sourceList = [2.2587, 295, 1.3422, 183, 0.6159, 50, 0.4887, 14,
              1.1474, 90, 7.5492, 2969, 2.0532, 374, 0.6363, 67, 3.1504, 378,
              10.3136, 1886]
print(sourceList)

[2.2587, 295, 1.3422, 183, 0.6159, 50, 0.4887, 14, 1.1474, 90, 7.5492, 2969, 2.0532, 374, 0.6363, 67, 3.1504, 378, 10.3136, 1886]


In [82]:
myData = np.array(sourceList)
print(myData)

[   2.259  295.       1.342  183.       0.616   50.       0.489   14.
    1.147   90.       7.549 2969.       2.053  374.       0.636   67.
    3.15   378.      10.314 1886.   ]


In [83]:
myData = np.reshape(myData,(10,2))
print(myData)

[[   2.259  295.   ]
 [   1.342  183.   ]
 [   0.616   50.   ]
 [   0.489   14.   ]
 [   1.147   90.   ]
 [   7.549 2969.   ]
 [   2.053  374.   ]
 [   0.636   67.   ]
 [   3.15   378.   ]
 [  10.314 1886.   ]]


In [84]:
print(myData.ndim)
print(myData.shape)

2
(10, 2)


In [85]:
for i in range(len(myData)):
    v = myData[i]
    for j in range(len(v)):
        print(i,j,v[j])

0 0 2.2587
0 1 295.0
1 0 1.3422
1 1 183.0
2 0 0.6159
2 1 50.0
3 0 0.4887
3 1 14.0
4 0 1.1474
4 1 90.0
5 0 7.5492
5 1 2969.0
6 0 2.0532
6 1 374.0
7 0 0.6363
7 1 67.0
8 0 3.1504
8 1 378.0
9 0 10.3136
9 1 1886.0


In [86]:
extractedArray = [myData[1], myData[2], myData[3]]
print(extractedArray)


[array([  1.342, 183.   ]), array([ 0.616, 50.   ]), array([ 0.489, 14.   ])]


In [87]:
transposeExtract = np.transpose(extractedArray)
print(transposeExtract)


[[  1.342   0.616   0.489]
 [183.     50.     14.   ]]


In [88]:
mulTransposeExtract = np.multiply(transposeExtract,10)
print(mulTransposeExtract)

[[  13.422    6.159    4.887]
 [1830.     500.     140.   ]]


In [89]:
alteredTransposeExtract = transposeExtract + mulTransposeExtract
# alteredTransposeExtract = np.add(transposeExtract, mulTransposeExtract)
print(alteredTransposeExtract)

[[  14.764    6.775    5.376]
 [2013.     550.     154.   ]]


In [90]:
# that transposeExtract is on top and alteredTransposeExtract is on the bottom. Bind the result to a
# variable named bigArray.
bigArray = np.vstack((transposeExtract,alteredTransposeExtract))
print(bigArray)


[[   1.342    0.616    0.489]
 [ 183.      50.      14.   ]
 [  14.764    6.775    5.376]
 [2013.     550.     154.   ]]


In [91]:
# variable, negBigArray
negBigArray = np.negative(bigArray)
print(negBigArray)

[[   -1.342    -0.616    -0.489]
 [ -183.      -50.      -14.   ]
 [  -14.764    -6.775    -5.376]
 [-2013.     -550.     -154.   ]]


In [92]:
# additional parameter) of myArray for EACH COLUMN. This should result in a 2x1 matrix.
# Bind it to the variable ‘arrayStdDev’
# ???
# arrayStdDev = np.std(bigArray,axis=0)
# arrayStdDev = np.std(alteredTransposeExtract,axis=1)
# arrayStdDev = np.std(transposeExtract,axis=1)
# arrayStdDev = np.std(extractedArray,axis=0)
arrayStdDev = np.std(myData,axis=0)
print(arrayStdDev)


[  3.153 938.827]
